POSSIBLE_DOMAINS = [
    "agriculture-and-agritech",
    "ai-and-machine-learning",
    "architecture-and-construction",
    "automotive",
    "aviation-marine-and-railroad",
    "biotechnology",
    "business-intelligence-and-analytics",
    "chemical-and-materials-science",
    "consumer-goods-and-retail",
    "cryptocurrencies-and-blockchain",
    "customer-relationship-management",
    "cybersecurity",
    "defense-and-aerospace",
    "document-and-content-management",
    "education-and-edtech",
    "electronics-and-hardware",
    "energy-environment-and-sustainability",
    "entertainment-and-media",
    "financial-services-and-banking",
    "food-and-beverage",
    "gaming-and-gambling",
    "government-and-public-services",
    "healthcare-and-pharmaceutical",
    "hospitality-and-travel",
    "human-resources-and-recruitment",
    "insurance",
    "iot-and-smart-devices",
    "legal-and-compliance",
    "logistics-and-supply-chain",
    "manufacturing-and-industrial-automation",
    "marketing-and-communications",
    "mining-and-natural-resources",
    "mobile-applications",
    "nonprofits-and-charities",
    "petcare-and-veterinary",
    "publishing-and-content",
    "real-estate-and-property",
    "religious-organizations",
    "science-and-research",
    "security-and-investigations",
    "social-networks-and-communications",
    "sports-and-fitness",
    "telecom-and-networking",
    "transport-and-logistics",
    "wellness-and-health"
]

OLD_TAGS = [
    "iot-and-smart-devices",
    "mobile-applications",
    "religious-organizations",
    "cryptocurrencies-and-blockchain",
    "customer-relationship-management",
    "document-and-content-management",
    "ai-and-machine-learning",
    "aws",
    "azure",
    "gcp",
    "salesforce",
    "artificial-intelligence-and-machine-learning",
    "sap",
    "dynamics-365",
    "native-mobile-apps",
    "flutter",
    "react-native",
    "unity-unreal-engine",
    "machine-learning-frameworks",  # Covers TensorFlow, PyTorch, scikit-learn
    "docker-kubernetes",
    "infrastructure-as-code",  # Covers Ansible, Terraform
    "ci-cd-tools",  # Covers Jenkins, CircleCI, GitHub Actions
    "big-data-frameworks",  # Covers Apache Spark, Hadoop
    "databases",  # Covers MongoDB, PostgreSQL, MySQL, Oracle-DB, SQL-Server, Redis
    "search-and-streaming",  # Covers Elasticsearch, RabbitMQ, Kafka
    "web-servers",  # Covers NGINX, Apache
    "api-architecture",  # Covers REST, GraphQL, gRPC
    "blockchain-solutions",  # Covers Ethereum, Hyperledger, Solidity
    "bi-tools",  # Covers Power BI, Tableau, Qlik
    "serverless-computing",  # Covers AWS Lambda, Azure Functions
    "edge-computing",
    "iot",
    "vr-ar",
    "cybersecurity",  # Covers SIEM, IAM, encryption
    "compliance-tools",  # Covers PCI-DSS, GDPR
    "event-driven-architecture",
    "microservices",
    "headless-cms",  # Covers Contentful, Strapi
    "auth-tools",  # Covers Auth0, Okta
    "collaboration-tools",  # Covers Jira, Confluence, SharePoint
    "integration-platforms",  # Covers Mulesoft, Boomi, Talend
    "data-pipelines",  # Covers Databricks, Apache Airflow
    "agriculture-and-agritech",
    "architecture-and-construction",
    "automotive",
    "aviation-marine-and-railroad",
    "biotechnology",
    "chemical-and-materials-science",
    "religious-organizations",
    "consumer-goods-and-retail",
    "cybersecurity",
    "defense-and-aerospace",
    "education-and-edtech",
    "electronics-and-hardware",
    "energy-environment-and-sustainability",
    "entertainment-and-media",
    "financial-services-and-banking",
    "food-and-beverage",
    "gaming-and-gambling",
    "government-and-public-services",
    "healthcare-and-pharmaceutical",
    "hospitality-and-travel",
    "human-resources-and-recruitment",
    "insurance",
    "internet-and-software",
    "legal-and-compliance",
    "logistics-and-supply-chain",
    "manufacturing-and-industrial-automation",
    "marketing-and-communications",
    "mining-and-natural-resources",
    "nonprofits-and-charities",
    "petcare-and-veterinary",
    "publishing-and-content",
    "real-estate-and-property",
    "science-and-research",
    "security-and-investigations",
    "social-networks-and-communications",
    "sports-and-fitness",
    "telecom-and-networking",
    "transport-and-logistics",
    "wellness-and-health"
]
